In [1]:
import numpy
numpy.random.seed(1234)
x = numpy.arange(100)
y1 = numpy.cumsum(numpy.random.normal(loc=0.05, size=len(x)))
y2 = numpy.cumsum(numpy.random.normal(loc=0.05, size=len(x)))
y3 = numpy.cumsum(numpy.random.normal(loc=0.05, size=len(x)))

In [2]:
label_style={"text-anchor":"start", "-toyplot-anchor-shift":"5px"}

import toyplot
canvas = toyplot.Canvas()
axes = canvas.axes()
axes.plot(x, y1)
axes.text(x[-1], y1[-1], "Label Numero Uno", angle=0, style=label_style)
axes.plot(x, y2)
axes.text(x[-1], y2[-1], "The really long second label.", angle=-30, style=label_style)
axes.plot(x, y3)
axes.text(x[-1], y3[-1], "Label 3", angle=0, style=label_style)

[[ 5.  6.]] [[ 197.    6.]] [[ 197.   -6.]] [[ 5. -6.]]
[[ 5.  6.]] [[ 197.    6.]] [[ 197.   -6.]] [[ 5. -6.]]
[ 5.] [ 197.] [-6.] [ 6.]
[[ 5.  6.]] [[ 353.    6.]] [[ 353.   -6.]] [[ 5. -6.]]
[[ 7.33012702  2.69615242]] [[ 308.70696754 -171.30384758]] [[ 302.70696754 -181.69615242]] [[ 1.33012702 -7.69615242]]
[ 1.33012702] [ 308.70696754] [-2.69615242] [ 181.69615242]
[[ 5.  6.]] [[ 89.   6.]] [[ 89.  -6.]] [[ 5. -6.]]
[[ 5.  6.]] [[ 89.   6.]] [[ 89.  -6.]] [[ 5. -6.]]
[ 5.] [ 89.] [-6.] [ 6.]


In [3]:
import toyplot.text

In [4]:
toyplot.text.extents(["Hello"], [30], {"font-size":"12px", "text-anchor":"middle", "alignment-baseline":"middle"})

[[-30.   6.]] [[ 30.   6.]] [[ 30.  -6.]] [[-30.  -6.]]
[[-28.98076211  -9.80384758]] [[ 22.98076211  20.19615242]] [[ 28.98076211   9.80384758]] [[-22.98076211 -20.19615242]]
[-28.98076211] [ 28.98076211] [-20.19615242] [ 20.19615242]


(array([-28.98076211]),
 array([ 28.98076211]),
 array([-20.19615242]),
 array([ 20.19615242]))