In [1]:
import numpy
import toyplot.layout

**Shortest Paths**

In [2]:
toyplot.layout._floyd_warshall_shortest_path(2, numpy.array([[0, 1]]))

array([[  0.,   1.],
       [ inf,   0.]])

In [3]:
toyplot.layout._floyd_warshall_shortest_path(3, numpy.array([[0, 1], [1, 2]]))

array([[  0.,   1.,   2.],
       [ inf,   0.,   1.],
       [ inf,  inf,   0.]])

In [4]:
toyplot.layout._floyd_warshall_shortest_path(3, numpy.array([[0, 1], [1, 2], [2, 0]]))

array([[ 0.,  1.,  2.],
       [ 2.,  0.,  1.],
       [ 1.,  2.,  0.]])

**Adjacency Lists**

In [5]:
toyplot.layout._adjacency_list(2, numpy.array([[0, 1]]))

[[1], []]

In [6]:
toyplot.layout._adjacency_list(2, numpy.array([[0, 1], [1, 2]]))

[[1], [2]]

In [7]:
toyplot.layout._adjacency_list(2, numpy.array([[0, 1], [1, 2], [0, 2]]))

[[1, 2], [2]]