In [1]:
import numpy
import toyplot.layout

**Shortest Paths**

In [2]:
toyplot.layout._floyd_warshall_shortest_path(2, numpy.array([[0, 1]]))

array([[  0.,   1.],
       [ inf,   0.]])

In [3]:
toyplot.layout._floyd_warshall_shortest_path(3, numpy.array([[0, 1], [1, 2]]))

array([[  0.,   1.,   2.],
       [ inf,   0.,   1.],
       [ inf,  inf,   0.]])

In [4]:
toyplot.layout._floyd_warshall_shortest_path(3, numpy.array([[0, 1], [1, 2], [2, 0]]))

array([[ 0.,  1.,  2.],
       [ 2.,  0.,  1.],
       [ 1.,  2.,  0.]])

**Adjacency Lists**

In [5]:
edges = numpy.array([[0, 1]])
toyplot.graph(edges, width=200);
print toyplot.layout._adjacency_list(2, edges)

INFO:toyplot:Graph layout time: 67.079782486 ms


[[1], []]


In [6]:
edges = numpy.array([[0, 1], [1, 2]])
toyplot.graph(edges, width=200);
print toyplot.layout._adjacency_list(3, edges)

INFO:toyplot:Graph layout time: 42.2101020813 ms


[[1], [2], []]


In [7]:
edges = numpy.array([[0, 1], [1, 2], [0, 2]])
toyplot.graph(edges, width=200);
print toyplot.layout._adjacency_list(3, edges)

INFO:toyplot:Graph layout time: 41.699886322 ms


[[1, 2], [2], []]


**Tree Detection**

In [8]:
edges = numpy.array([[0, 1]])
toyplot.graph(edges, width=200);
print toyplot.layout._require_tree(toyplot.layout._adjacency_list(2, edges))

INFO:toyplot:Graph layout time: 39.8578643799 ms


(0, 1)


In [9]:
edges = numpy.array([[0, 1], [0, 2]])
toyplot.graph(edges, width=200);
print toyplot.layout._require_tree(toyplot.layout._adjacency_list(3, edges))

INFO:toyplot:Graph layout time: 40.5411720276 ms


(0, 1)


In [10]:
edges = numpy.array([[0, 1], [1, 2]])
toyplot.graph(edges, width=200);
print toyplot.layout._require_tree(toyplot.layout._adjacency_list(3, edges))

INFO:toyplot:Graph layout time: 43.3399677277 ms


(0, 2)


In [11]:
edges = numpy.array([[0, 1], [1, 2], [2, 1]])
toyplot.graph(edges, width=200, layout=toyplot.layout.FruchtermanReingold(toyplot.layout.CurvedEdges()));
print toyplot.layout._require_tree(toyplot.layout._adjacency_list(3, edges))

INFO:toyplot:Graph layout time: 40.3261184692 ms


ValueError: Not a tree.