In [1]:
import toyplot.data
import numpy

In [2]:
table = toyplot.data.Table()
table["x"] = numpy.arange(10)
table["x*2"] = table["x"] * 2
table["x^2"] = table["x"] ** 2
table

A Toyplot table behaves like a Python dict that maps column names (keys) to the column values (1D arrays).  For example, you assign and access individual columns using normal indexing notation with column names:

In [3]:
print(table["x"])
print(table["x*2"])
print(table["x^2"])

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
[ 0  1  4  9 16 25 36 49 64 81]


In addition, the `keys()`, `values()`, and `items()` methods also act like their standard library counterparts, providing column-oriented access to the table contents.  However, unlike a normal Python dict, a Toyplot table remembers the order in which columns were added to the table, and always returns them in the same order:

In [4]:
for name in table.keys():
    print(name)

x
x*2
x^2


In [5]:
for column in table.values():
    print(column)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
[ 0  1  4  9 16 25 36 49 64 81]


In [6]:
for name, column in table.items():
    print(name, column)

x [0 1 2 3 4 5 6 7 8 9]
x*2 [ 0  2  4  6  8 10 12 14 16 18]
x^2 [ 0  1  4  9 16 25 36 49 64 81]


That's all straightforward, but Toyplot tables also behave like Python lists.  For example, you can use the normal Python length function to get the number of rows:

In [7]:
len(table)

10

And you can access a single row using its integer index:

In [8]:
table[3]

And you can retrieve a range of rows using slice notation:

In [9]:
table[2:5]

You can also retrieve a noncontiguous range of rows using Numpy advanced slicing:

In [10]:
table[[1, 3, 4]]

Finally, you can mix both forms of indexing (rows and columns) to retrieve arbitrary subsets of a table:

In [11]:
table[3, "x*2"]

In [12]:
table[3:6, ["x", "x*2"]]

In [13]:
table[[1, 3, 4], ["x", "x*2"]]

Passing a sequence of column names allows you to reorder the columns in a table if necessary:

In [14]:
table[["x*2", "x"]]

Note that all of these operations are taking views into the underlying column storage, so no data is copied.

In [15]:
data = dict()
data["Name"] = ["Tim", "Fred", "Jane"]
data["Age"] = [45, 32, 43]
toyplot.data.Table(data)

You can also pass any other object that implements Python's :class:`collections.abc.Mapping` protocol.  Note that the columns are inserted into the table in alphabetical order, since Python dictionaries / maps do not have an explicit ordering.

If column order matters to you, you can use an instance of :class:`collections.OrderedDict` instead, which remembers the order in which data was added:

In [16]:
import collections
data = collections.OrderedDict()
data["Name"] = ["Tim", "Fred", "Jane"]
data["Age"] = [45, 32, 43]
toyplot.data.Table(data)

Another way to add ordered data to a data table would be to use a sequence of (column name, column values) tuples:

In [17]:
data = [("Name", ["Tim", "Fred", "Jane"]), ("Age", [45, 32, 43])]
toyplot.data.Table(data)

Again, you can use any :class:`collections.abc.Sequence` type, not just a Python list as in this example.

You can also treat any two-dimensional numpy array (matrix) as a table:

In [18]:
data = numpy.array([["Tim", 45],["Fred", 32], ["Jane", 43]])
toyplot.data.Table(data)

... Note that the ordering of the matrix columns is retained, and column names are created for you.

You can also convert a [Pandas](http://pandas.pydata.org) data frame into a table:

In [19]:
import pandas
df = pandas.read_csv(toyplot.data.temperatures.path)
toyplot.data.Table(df)[0:5]

By default, the data frame index isn't included in the conversion to a table, but you can override this if you wish:

In [20]:
toyplot.data.Table(df, index=True)[0:5]

If you don't like the auto generated name of the index column, you can provide an alternate name of your own:

In [21]:
toyplot.data.Table(df, index="INDEX")[0:5]

Note that hierarchical data frame indices will be converted to multiple table columns.

In [22]:
table = toyplot.data.read_csv(toyplot.data.temperatures.path)
table[0:10]

Then, we convert the readings (which are stored as tenths of a degree Celsius) to Fahrenheit:

In [23]:
table["TMAX_F"] = ((table["TMAX"].astype("float64") * 0.1) * 1.8) + 32
table["TMIN_F"] = ((table["TMIN"].astype("float64") * 0.1) * 1.8) + 32

Finally, we can pass table columns directly to Toyplot for plotting:

In [24]:
canvas = toyplot.Canvas(width=600, height=300)
axes = canvas.cartesian(xlabel="Day", ylabel=u"Temperature \u00b0F")
axes.plot(table["TMAX_F"], color="red", stroke_width=1)
axes.plot(table["TMIN_F"], color="blue", stroke_width=1);

<path d="M 50.0 176.31578947368422 L 51.25 189.5585738539898 L 52.5 185.82342954159594 L 53.75 185.82342954159594 L 55.0 182.08828522920206 L 56.25 174.61799660441426 L 57.5 170.54329371816638 L 58.75 155.60271646859081 L 60.0 165.11035653650254 L 61.25 159.33786078098473 L 62.5 174.61799660441426 L 63.75 193.29371816638371 L 65.0 195.33106960950764 L 66.25 202.80135823429541 L 67.5 208.57385398981324 L 68.75 182.08828522920206 L 70.0 157.64006791171477 L 71.25 151.86757215619696 L 72.5 155.60271646859081 L 73.75 149.830220713073 L 75.0 153.56536502546692 L 76.25 140.6621392190153 L 77.5 144.39728353140919 L 78.75 157.64006791171477 L 80.0 144.39728353140919 L 81.25 148.13242784380307 L 82.5 189.5585738539898 L 83.75 176.31578947368422 L 85.0 153.56536502546692 L 86.25 148.13242784380307 L 87.5 142.35993208828526 L 88.75 151.86757215619696 L 90.0 148.13242784380307 L 91.25 138.62478777589135 L 92.5 138.62478777589135 L 93.75 144.39728353140919 L 95.0 144.39728353140919 L 96.25 155.60271646859081 L 97.5 170.54329371816638 L 98.75 165.11035653650254 L 100.0 176.31578947368422 L 101.25 165.11035653650254 L 102.5 159.33786078098473 L 103.75 153.56536502546692 L 105.0 142.35993208828526 L 106.25 140.6621392190153 L 107.5 157.64006791171477 L 108.75 136.58743633276742 L 110.0 153.56536502546692 L 111.25 163.07300509337864 L 112.5 174.61799660441426 L 113.75 159.33786078098473 L 115.0 174.61799660441426 L 116.25 163.07300509337864 L 117.5 168.84550084889645 L 118.75 165.11035653650254 L 120.00000000000001 155.60271646859081 L 121.25 140.6621392190153 L 122.5 129.11714770797965 L 123.75 123.68421052631579 L 125.0 134.88964346349746 L 126.25 138.62478777589135 L 127.5 127.41935483870969 L 128.75 119.60950764006792 L 130.0 136.58743633276742 L 131.25 166.8081494057725 L 132.5 153.56536502546692 L 133.75 136.58743633276742 L 135.0 125.38200339558574 L 136.25 119.60950764006792 L 137.5 108.40407470288628 L 138.75 102.63157894736842 L 140.0 115.87436332767405 L 141.25 123.68421052631579 L 142.5 129.11714770797965 L 143.75 132.85229202037351 L 145.0 132.85229202037351 L 146.25 119.60950764006792 L 147.5 129.11714770797965 L 148.75 174.61799660441426 L 150.0 155.60271646859081 L 151.25 146.09507640067912 L 152.5 127.41935483870969 L 153.75 115.87436332767405 L 155.0 112.13921901528019 L 156.25 112.13921901528019 L 157.5 114.17657045840409 L 158.75 112.13921901528019 L 160.0 112.13921901528019 L 161.25 121.64685908319188 L 162.5 125.38200339558574 L 163.75 112.13921901528019 L 165.0 106.7062818336163 L 166.25 108.40407470288628 L 167.5 112.13921901528019 L 168.75 106.7062818336163 L 170.0 155.60271646859081 L 171.25 161.37521222410868 L 172.5 132.85229202037351 L 173.75 119.60950764006792 L 175.0 110.44142614601023 L 176.25 106.7062818336163 L 177.5 100.93378607809846 L 178.75 98.896434634974554 L 180.0 140.6621392190153 L 181.25 161.37521222410868 L 182.5 131.15449915110358 L 183.75 123.68421052631579 L 185.0 115.87436332767405 L 186.25 98.896434634974554 L 187.5 125.38200339558574 L 188.75 121.64685908319188 L 190.00000000000003 114.17657045840409 L 191.24999999999997 110.44142614601023 L 192.5 106.7062818336163 L 193.75 98.896434634974554 L 195.0 91.42614601018677 L 196.25 87.691001697792899 L 197.5 97.198641765704608 L 198.75 134.88964346349746 L 200.0 125.38200339558574 L 201.25 106.7062818336163 L 202.5 112.13921901528019 L 203.75 121.64685908319188 L 205.0 108.40407470288628 L 206.25 121.64685908319188 L 207.5 114.17657045840409 L 208.75 119.60950764006792 L 210.0 112.13921901528019 L 211.25 100.93378607809846 L 212.5 93.463497453310737 L 213.75 87.691001697792899 L 215.0 89.728353140916809 L 216.25 85.653650254668932 L 217.5 87.691001697792899 L 218.75 102.63157894736842 L 220.0 110.44142614601023 L 221.25000000000003 112.13921901528019 L 222.49999999999997 102.63157894736842 L 223.75 87.691001697792899 L 225.0 78.183361629881148 L 226.25 83.955857385398971 L 227.5 80.220713073005115 L 228.75 85.653650254668932 L 230.0 91.426146010186